name: Ubuntu_18
 
on:
    release:
        branches: '*'
        
jobs:
  perl-job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-last]
        perl-version:
          - '5.24'
          - 'latest'
    runs-on: ${{ matrix.os }}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Regular tests
        run: |
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --author --missing | cpanm --notest
          dzil test --author --release --verbose
